In [1]:
import numpy as np

In [2]:
# You want to remove a certain substring, e.g. '314'
def xrange(n):
    return np.array((np.arange(10**n, 10**(n++1))))

In [3]:
s=xrange(1)
s

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [4]:
def filter(x, func):
    return [x for x in s if func(x)]

In [5]:
filter(s, func=lambda x: str(x)=='42')

[42]

In [6]:
# expand the standard str class with a contains method
# not a good idea, leading 0!

class String(str):
    def contains(self, x):
        return self.find(str(x)) >= 0 
    
    @property
    def num_digits(self):
        return len(self)
    
    @property
    def shift(self):
        return String(int(self)/10)
    
class Set(set):
    def add(self, x):
        return Set({10*a + y for a in self for y in x})

In [7]:
T=np.matrix([[0, 1, 0, 1, 0, 1, 0, 1, 0, 1]])
T

matrix([[0, 1, 0, 1, 0, 1, 0, 1, 0, 1]])

In [8]:
xxx = "1809410"
len(xxx)
# all other endings
# set ending in 1
# set ending in 18
# set ending in 180
# set ending in 1809
# set ending in 18094
# set ending in 180941

7

In [9]:
for n in range(0, 2):
    print(n)
    s = xrange(n)
    print(s)

0
[1 2 3 4 5 6 7 8 9]
1
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [10]:
"314"
# all other endings S1, attach 3 get S2
# set ending in 3 attach 1 get S3, attach 3 get S2 
# set ending in 31  forbid to attach 4, attach 3 get S2, 

'314'

In [11]:
# Once T is given...
T=np.array([[1,1,1,2,1,1,1,1,1,1],[1,3,1,2,1,1,1,1,1,1],[1,1,1,2,0,1,1,1,1,1]])

In [12]:
T

array([[1, 1, 1, 2, 1, 1, 1, 1, 1, 1],
       [1, 3, 1, 2, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 2, 0, 1, 1, 1, 1, 1]])

In [13]:
a=np.multiply((T[1,:]==1), np.arange(0,10))
a[a > 0]

array([2, 4, 5, 6, 7, 8, 9])

In [14]:
a = np.unique(T[:])
unique = a[a > 0]
unique

array([1, 2, 3])

In [15]:
S = dict()
digits = 6
for u in unique:
    S[u] = {n: set() for n in range(1,digits)}

In [16]:
# go over the first row of T
for i in range(1, 10):
    S[T[0,i]][1].add(i) 
S

{1: {1: {1, 2, 4, 5, 6, 7, 8, 9}, 2: set(), 3: set(), 4: set(), 5: set()},
 2: {1: {3}, 2: set(), 3: set(), 4: set(), 5: set()},
 3: {1: set(), 2: set(), 3: set(), 4: set(), 5: set()}}

In [17]:
def f(ss, x):
    return {10*a + x for a in ss}


for n in range(2, digits):
    for s, row in enumerate(T, 1):
        for k, w in enumerate(row):
            if w > 0:          
                S[w][n] = S[w][n].union(f(S[s][n-1], k))

S
            

{1: {1: {1, 2, 4, 5, 6, 7, 8, 9},
  2: {10,
   11,
   12,
   14,
   15,
   16,
   17,
   18,
   19,
   20,
   21,
   22,
   24,
   25,
   26,
   27,
   28,
   29,
   30,
   32,
   34,
   35,
   36,
   37,
   38,
   39,
   40,
   41,
   42,
   44,
   45,
   46,
   47,
   48,
   49,
   50,
   51,
   52,
   54,
   55,
   56,
   57,
   58,
   59,
   60,
   61,
   62,
   64,
   65,
   66,
   67,
   68,
   69,
   70,
   71,
   72,
   74,
   75,
   76,
   77,
   78,
   79,
   80,
   81,
   82,
   84,
   85,
   86,
   87,
   88,
   89,
   90,
   91,
   92,
   94,
   95,
   96,
   97,
   98,
   99},
  3: {100,
   101,
   102,
   104,
   105,
   106,
   107,
   108,
   109,
   110,
   111,
   112,
   114,
   115,
   116,
   117,
   118,
   119,
   120,
   121,
   122,
   124,
   125,
   126,
   127,
   128,
   129,
   130,
   132,
   134,
   135,
   136,
   137,
   138,
   139,
   140,
   141,
   142,
   144,
   145,
   146,
   147,
   148,
   149,
   150,
   151,
   152,
   154,
   155,
   156,