In [1]:
import numpy as np
from kempner.util import create_S2, create_f, psi

In [7]:
T=np.array([[1,1,1,2,1,1,1,1,1,1],[1,3,1,2,1,1,1,1,1,1],[1,1,1,2,0,1,1,1,1,1]])
T

array([[1, 1, 1, 2, 1, 1, 1, 1, 1, 1],
       [1, 3, 1, 2, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 2, 0, 1, 1, 1, 1, 1]])

In [8]:
# Define a simple numpy array with two elements, each element is a set...
x=np.array([[{1,2,3,100}],[{1,2,3,4,5}]])
print(x)
psi(x, k=1, digits=50)

[[set([1, 2, 3, 100])]
 [set([1, 2, 3, 4, 5])]]


array([[1.8433333333333333333333333333333333333333333333333],
       [2.2833333333333333333333333333333333333333333333333]], dtype=object)

In [6]:
S=create_S2(matrix=T, digits=3)
S
print(S.shape)


xxx = {k: psi(S, k, digits=20) for k in range(1, 30)}
for key, item in xxx.items():
    print(key)
    print(item)

(3, 3)
1
[[2.4956349206349206349 2.0709505656246450354 2.0474555141779051213]
 [0.33333333333333333333 0.24520063353059222487 0.23203569201882636603]
 [0.00000000000000000000 0.032258064516129032258 0.024417423338196986197]]
2
[[1.4286566200554295792 0.083752577903769157307 0.0080181438111910791699]
 [0.11111111111111111111 0.010323008388256274444 0.00091932639923225834145]
 [0.00000000000000000000 0.0010405827263267429761 0.00010205388695762546022]]
3
[[1.1594949486371562146 0.0048468092368463129380 0.000044244989958844970353]
 [0.037037037037037037037 0.00059403856391782827916
  5.1424940665224186449e-6]
 [0.00000000000000000000 0.000033567184720217515357
  5.8221500663898235735e-7]]
4
[[1.0695909044814108678 0.00034524720642284091578 2.9884525173207006021e-7]
 [0.012345679012345679012 0.000039981831883473995705
  3.5199822555392513811e-8]
 [0.00000000000000000000 1.0828124103295972696e-6 3.8848887828169501995e-9]]
5
[[1.0327821150072448964 0.000027491026871113471050 2.25334247322626

In [9]:
T

array([[1, 1, 1, 2, 1, 1, 1, 1, 1, 1],
       [1, 3, 1, 2, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 2, 0, 1, 1, 1, 1, 1]])

In [13]:
f = create_f(T)
print(f)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2,
       3, 5, 6, 7, 8, 9])

In [14]:
f = np.zeros((T.shape[0], T.shape[0], T.shape[1]))

In [15]:
f

array([[[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]]])

In [21]:
for ii,jj in zip(i,j):
    print(ii, jj)
    print(T[ii,jj])
    f[T[ii,jj]-1,ii,jj]=1

(0, 0)
1
(0, 1)
1
(0, 2)
1
(0, 3)
2
(0, 4)
1
(0, 5)
1
(0, 6)
1
(0, 7)
1
(0, 8)
1
(0, 9)
1
(1, 0)
1
(1, 1)
3
(1, 2)
1
(1, 3)
2
(1, 4)
1
(1, 5)
1
(1, 6)
1
(1, 7)
1
(1, 8)
1
(1, 9)
1
(2, 0)
1
(2, 1)
1
(2, 2)
1
(2, 3)
2
(2, 5)
1
(2, 6)
1
(2, 7)
1
(2, 8)
1
(2, 9)
1


In [22]:
f

array([[[ 1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  0.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  0.,  0.,  1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]]])