In [1]:
import numpy as np
from kempner.util import  create_S3, create_f, psi, matrix_42, Psi_matrix, aCoeff

In [2]:
T = matrix_42()
T

array([[1, 1, 1, 1, 2, 1, 1, 1, 1, 1],
       [1, 1, 0, 1, 2, 1, 1, 1, 1, 1]])

In [3]:
f, A, B = create_f(T)
B

[89 80]
[10  9]

In [4]:
S=create_S3(matrix=T, digits=3)

In [5]:
Psi = Psi_matrix(S)

array([[2.578968253968253968253968253968253968253968253968253968253968253968253968253968253968253968253968254,
        0.2500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000],
       [2.089165372524314945249489228915914050113043304496775874542056949144004354617723051114913116696653419,
        0.2354343673375275377778506689645613300181510444338980008566992296654374251370496677129968744486892171],
       [2.031411671377980612717129460141903390135068056769603833861298271554181452485138432463700421213815011,
        0.2287629826143282734537377907978170156811509944343853048455950760408341104267787940268888795357942944],
       [0.000000000000000, 0.000000000000000],
       [0.000000000000000, 0.000000000000000],
       [0.000000000000000, 0.000000000000000],
       [0.000000000000000, 0.000000000000000],
       [0.000000000000000, 0.000000000000000],
       [0.000000000000000, 0.000000000000000],
       [0.000000000000000, 0.000000000000000],

In [6]:
# forward interpolate rows of Psi
for i in range(S.shape[0], Psi.shape[0]):
    for k in range(1, Psi.shape[2]):
        #if Psi[i-1,1,k]>0:
        for m in range(0, T.shape[1]):
            [J,L] = np.where(f[:,:,m]);
            for l,j in zip(L,J):
                for w in range(0, Psi.shape[2]-k):
                    Psi[i,j,k] = Psi[i,j,k]+aCoeff(k,w,m)*Psi[i-1,l,k+w]                    


In [7]:
Psi[:,:,1]

array([[2.578968253968253968253968253968253968253968253968253968253968253968253968253968253968253968253968254,
        0.2500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000],
       [2.089165372524314945249489228915914050113043304496775874542056949144004354617723051114913116696653419,
        0.2354343673375275377778506689645613300181510444338980008566992296654374251370496677129968744486892171],
       [2.031411671377980612717129460141903390135068056769603833861298271554181452485138432463700421213815011,
        0.2287629826143282734537377907978170156811509944343853048455950760408341104267787940268888795357942944],
       [222.276544878340, 24.8914906368008],
       [24279.2697596262, 2721.24815922570],
       [2.64986859839723e6, 297201.578860562],
       [2.89040441828577e8, 3.24338949998082e7],
       [3.15143915748890e10, 3.53756172875598e9],
       [3.43500561399881e12, 3.85685718934719e11],
       [3.74328902580615e14, 4.2037601705